# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        database_service:
            id: database_user_provider
#        in_memory:
#            memory:
#                users:
#                    ryan:
#                        password: $2a$12$LCY0MefVIEc3TYPHV9SNnuzOfyr2p/AXIGoQJEDs4am4JwhNz/jli
#                        roles: 'ROLE_USER'
#                    admin:
#                        password: $2a$12$cyTWeE9kpq1PjqKFiWUZFuCRPwVyAZwm4XzMZ1qPUFl7/flCM3V0G
#                        roles: 'ROLE_ADMIN'

    encoders:
        AppBundle\Entity\security\DatabaseUser:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false
#        Symfony\Component\Security\Core\User\User:
#            algorithm: bcrypt
#            cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login_firewall:
            pattern:   ^/login$
            anonymous: ~
        default:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
                success_handler: success_handler
            logout:
                path:   /logout
                target: /

        # main:
            # anonymous: ~

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/sensor/list, roles: [ROLE_ADMIN, ROLE_TECH, ROLE_MNGR] }
        - { path: ^/sensor/find, roles: [ROLE_ADMIN, ROLE_TECH, ROLE_MNGR] }
        - { path: ^/sensor, roles: [ROLE_ADMIN, ROLE_TECH] }
        - { path: ^/reports, roles: [ROLE_ADMIN, ROLE_MNGR] }
        - { path: ^/register, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
